services:
  # Backend service (FastAPI)
  - type: web
    name: todo-fastapi-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000
    envVars:
      - key: postgresql+psycopg2://todolist_django_render_pqsu_user:0WNrhPMDSLxLPkX65wUXUwH266NARXx5@dpg-cvnu4mruibrs73aeldg0-a.singapore-postgres.render.com/todolist_django_render_pqsu?sslmode=require
        fromDatabase:
          name: todolist-django-render
          property: connectionString

  # Frontend service (React)
  - type: web
    name: todo-react-frontend
    runtime: node
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist  # Vite/React builds to `dist`
    envVars:
      - key: VITE_API_BASE_URL
        sync: false  # Manually set this to your backend URL